### ISSUE TITLE
Dashboard grid sluggish/freezing

### ISSUE THREAD

**Issue by Bia10** [excubo-ag/Blazor.Grids#19]
This has been noticed by [edgarssults](https://github.com/edgarssults) already i have asked him about it recently in https://github.com/edgarssults/Bannerboard/issues/1

If you try to move rapidly with components of dashboard they move very sluggishly or even come to complete freeze.

This behavior can be replicated at your demo:

https://excubo-ag.github.io/Blazor.Grids/dashboard

![image](https://user-images.githubusercontent.com/2548763/171953373-7e040e8a-4cb6-4128-bd9c-0504c77747e7.png)

as you can see the page has entirely frozen!

**Comment by stefanloerwald** [comment]
Hi @Bia10,

I've identified the [overlap resolution algorithm](https://github.com/excubo-ag/Blazor.Grids/blob/12954a5928c32c3af76f9e6317dcaf8e3261984b/Grid/Grid.razor.cs#L145) as the culprit. When an element is moved or resized, the other elements are supposed to "get out of the way", as there shouldn't be overlaps. It turns out that this algorithm seems to get stuck in an infinite loop sometimes. I don't have the time at the moment to figure out why, so if this is something that you need fixed, I'd encourage you to try and solve this and contribute your fix as a PR.

If you can live without the overlap resolution, the easy alternative is to ditch Dashboard in favor of Grid. [Dashboard](https://github.com/excubo-ag/Blazor.Grids/blob/12954a5928c32c3af76f9e6317dcaf8e3261984b/Grid/Dashboard.cs) is only a thin wrapper around it anyway.

Thanks,
Stefan

**Comment by Bia10** [comment]
Thanks for quick reply,

Id love to take a look at this but, unfortunately i am in similar position "I don't have the time at the moment to figure out why".

Just to be clear there seem to be 2 issues at hand:

1.  The movement/resizing of components of dashboard is very slow/sluggish.
2.  The overlap algorithm getting stuck in infinite loop.

**Comment by stefanloerwald** [comment]
I suspect the sluggish behavior you're seeing has the same underlying cause (i.e. the overlap resolution goes into many iterations, sometimes even infinite). Probably the best approach is to completely replace that code with some new logic.

**Comment by edgarssults** [comment]
The fix seems to be working well (using 3.0.32 currently). No more freezing or crashing. 👍

**Comment by stefanloerwald** [comment]
Thanks for the feedback, @edgarssults
