### ISSUE TITLE
AllowMove and AllowResize requires AspectRatio

### ISSUE THREAD

**Issue by owaits** [excubo-ag/Blazor.Grids#24]
If you try to set the AllowMove or AllowResize parameters without having set the aspect ratio then you get a rather difficult to interpret JS exception when you run the code. 

Either this should be made to work or when you set the AllowMove and AllowResize parameters it should throw an exception if the AspectRatio parameters has not been set. This would then give a more meaningful exception that implementers can use to correct their code. Alas I don't think optional [EditorRequired]  is a thing yet.

I am happy to put up a PR with this change but I thought maybe some discussion over what is the best way to handle this might be required.

**Comment by stefanloerwald** [comment]
Hi @owaits,

Sorry for the long delay. I agree that an exception is never a great dev experience for something that should in an ideal world be enforced at compile time. AFAIK, conditional required params aren't a thing, so that's out. The behavior is documented on AllowMove/AllowResize. Where would you throw the exception?

Thanks,
Stefan
